name: python_data_science
channels:
  - conda-forge
dependencies:
  - python=3.12
  - black=24.4.2
  - flake8=7.0.0
  - isort=5.13.2
  - pip=24.2
  - ipython=8.15.0
  - jupyterlab=4.0.11
  - matplotlib=3.8.4
  - notebook=7.0.8
  - numpy=1.26.4
  - pandas=2.2.2
  - seaborn=0.13.2
  - pip:
    - python-dotenv
    - -e .